name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t portaljobs/portal-backend .
      - name: Publish image to docker hub
        run: docker push portaljobs/portal-backend:latest
        
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Pull image from docker hub
        run: docker pull portaljobs/portal-backend:latest

      - name: Delete old container
        run: docker rm -f portal-backend-container
        
      - name: Write .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Docker container
        run: |
          docker run -d \
            --env-file .env \
            -p 3000:3001 \
            --name portal-backend-container \
            portaljobs/portal-backend:latest

      - name: Cleanup .env file
        run: rm -f .env
